---
title: "Bachelor thesis"
author: "Isac Jonsson & Andrea Breuer"
date: "2022-10-06"
output: 
#html_document
  pdf_document:
    keep_tex: yes 
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)

library(kableExtra) #Here I put any libraries that I will use
library('tinytex')
library(ggplot2)
library(knitr)
library('latex2exp')
library("Lock5Data")
library('DescTools')
library(HSAUR)
library('ResourceSelection')
library('cowplot')
library(dplyr)
library(readxl)
library(foreign)
library(MASS)
library(Hmisc)
library(reshape2)
library(car)
library(ordinal)
library(brant)
```

```{r}
# Loading the dataframes

windowsFonts(Times=windowsFont("Times New Roman"))

df <- read.csv('dataset.csv')

df$housing <- ifelse(df$prompt == 'houseing', 1, 0)
df$atumn <- ifelse(df$prompt == 'weather', 1, 0)
df$boxes <- ifelse(df$prompt == 'bankruptcy', 1, 0)

anno_df <- read_excel("Image Annotation.xlsx",  sheet = "Annotation for Newsworthy Batch")

anno_df <- anno_df[1:4]
anno_df <- na.omit(anno_df)
colnames(anno_df) <- c('index', 'scale_1_5', 'publish', 'reason')
anno_df$publish <- as.numeric(anno_df$publish)

anno_df$publish_bin <- ifelse(anno_df$publish == 5 , 1, 0)



df_tot <- merge(df, anno_df, by = 'index')


```

```{r}
# Descriptive table 

# Lägg till pubilshable!
scale_mean <- mean(df_tot$scale_1_5)
guidance_mean <- mean(df$guidance)
inf_step_mean <- mean(df$inf_steps) 
xtra_prompt_mean <- mean(df$xtra_prompt)
housing_mean <- mean(df$housing)
atumn_mean <- mean(df$atumn)
boxes_mean <- mean(df$boxes)

MEAN <- rbind(scale_mean, guidance_mean, inf_step_mean, xtra_prompt_mean, housing_mean, atumn_mean, boxes_mean)

scale_sd <- sd(df_tot$scale_1_5)
guidance_sd <- sd(df$guidance) 
inf_step_sd <- sd(df$inf_steps)
xtra_prompt_sd <- "-"
housing_sd <- "-"
atumn_sd <- "-"
boxes_sd <- "-"

SD <- rbind(scale_sd, guidance_sd, inf_step_sd, xtra_prompt_sd, housing_sd, atumn_sd, boxes_sd) 

scale_min <- min(df_tot$scale_1_5)
guidance_min <- min(df$guidance)
inf_step_min <- min(df$inf_steps)
xtra_prompt_min <- min(df$xtra_prompt)
housing_min <- min(df$housing)
atumn_min <- min(df$atumn)
boxes_min <- min(df$boxes)

MIN <- rbind(scale_min, guidance_min, inf_step_min, xtra_prompt_min, housing_min, atumn_min, boxes_min)

scale_max <- max(df_tot$scale_1_5)
guidance_max <- max(df$guidance)
inf_step_max <- max(df$inf_steps)
xtra_prompt_max <- max(df$xtra_prompt)
housing_max <- max(df$housing)
atumn_max <- max(df$atumn)
boxes_max <- max(df$boxes)

MAX <- rbind(scale_max, guidance_max, inf_step_max, xtra_prompt_max, housing_max, atumn_max, boxes_max)


scale_n <- sum(with(df_tot, is.na(scale_1_5) == F))
guidance_n <- sum(with(df_tot, is.na(guidance) == F))
inf_step_n <- sum(with(df_tot, is.na(inf_steps) == F))
xtra_prompt_n <- sum(with(df_tot, is.na(xtra_prompt) == F))
housing_n <- sum(with(df_tot, is.na(housing) == F))
atumn_n <- sum(with(df_tot, is.na(atumn) == F))
boxes_n <- sum(with(df_tot, is.na(boxes) == F))

N <- rbind(scale_n, guidance_n, inf_step_n, xtra_prompt_n, housing_n, atumn_n, boxes_n)

scale_med <- median(df_tot$scale_1_5)
guidance_med <- median(df$guidance)
inf_step_med <- median(df$inf_steps) 
xtra_prompt_med <- "-"
housing_med <- "-"
atumn_med <- "-"
boxes_med <- "-"

MED <- rbind(scale_med, guidance_med, inf_step_med, xtra_prompt_med, housing_med, atumn_med, boxes_med)


sumtab <- as.data.frame(cbind(N,MEAN, MED, SD, MIN, MAX), row.names = c('Rating', 'Guidance scale', 'Iterations', 'Keywords', 'Housing', 'Atumn', 'Bankruptcy'))

sumtab$V2<- round(as.numeric(sumtab$V2), 2 )
sumtab$V4 <- c(round(as.numeric(sumtab$V4[1:3]), 2), sumtab$V4[c(4:7)])

kable(sumtab, caption = "Table X Descriptive statistics of the dataset",
      booktabs = TRUE, align ='c', col.names = c('N', 'Mean', 'Median', 'Std. error', 'Min' , 'Max'),  position = "h!") %>%
     column_spec(1,width = '3cm') %>%
      column_spec(2,width = '2cm') %>%
      column_spec(3,width = '2cm') %>%
      column_spec(4,width = '2cm') %>%
      column_spec(5,width = '2cm') %>%
      column_spec(6,width = '2cm') %>%
      column_spec(7,width = '2cm') %>%
   kable_styling(latex_options = "striped")

```

```{r}
# Log-uniform distribution for inf_steps

ggplot(df, aes(x=inf_steps)) +
  geom_histogram(binwidth = 5, color = "white", fill = "slategray") +
  theme_minimal() +
  xlab('Iterations') +
  ylab('Frequency') +
  coord_cartesian(expand = FALSE, xlim = c(45, 257), ylim = c(0, NA)) +
  theme(axis.text.x = element_text(size = 26), 
        axis.title.x = element_text(size = 34), axis.title.y = element_text(size = 34), axis.text.y = element_text(size = 26), text= element_text(family = 'Times'))

```

```{r}
# Barplot of reasons not to publish 

real <- sum(with(df_tot, reason == 'No, not realistic enough'))
style <- sum(with(df_tot, reason == 'No, wrong tone/style'))
other <- sum(with(df_tot, reason == 'No, other reason'))
comp <- sum(with(df_tot, reason == 'No, bad composition'))
qual <- sum(with(df_tot, reason == 'No, bad image quality'))
yes <- sum(with(df_tot, reason == 'Yes'))

bars <- data.frame(numbers = c(comp, qual, real, other, style, yes))

bars$text <- c('No, bad composition', 'No, bad image quality', 'No, not realistic enough', 'No, other reason', 'No, wrong tone/style', 'Yes')

ggplot(bars, aes(x=text, y= numbers)) + 
  geom_bar(fill = c("slategray", "slategray", "slategray", "slategray", "slategray", 'green4'), position = 'dodge', stat='identity', width = 0.85) +
  coord_flip() +
    geom_text(aes(label=numbers), position=position_dodge(width=0.9), vjust=0.5, hjust = -0.15,  size=9, family = 'Times') +
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 0, vjust = 0.5)) +
  ylim(0, 420) + 
  xlab(NULL) +
  ylab(NULL) +
  theme(axis.text.x = element_text(size = 16), 
        axis.title.x = element_text(size = 34), axis.text.y = element_text(size = 24), text= element_text(family = 'Times'))
```

```{r}
# Barplot av fördelningen i Scale_1_5

r1 <- sum(with(df_tot, scale_1_5 == 1))
r2 <- sum(with(df_tot, scale_1_5 == 2))
r3 <- sum(with(df_tot, scale_1_5 == 3))
r4 <- sum(with(df_tot, scale_1_5 == 4))
r5 <- sum(with(df_tot, scale_1_5 == 5))

rating <- data.frame(numbers = c(r1, r2, r3, r4, r5), scale = 1:5)

ggplot(rating, aes(x=scale, y=numbers )) + 
  geom_bar(fill = "slategray", width = 0.7, stat = "identity", position = 'dodge') +
  geom_text(aes(label=numbers), position=position_dodge(width=0.9), vjust=-0.25,  size=11, family = 'Times') +
  theme(axis.text.x = element_text(angle = 60, vjust = 0.5)) +
  theme_minimal() +
   ylim(0, 180) +
  xlab('Rating') +
  ylab(NULL) +
  theme(axis.text.x = element_text(size = 26), 
        axis.title.x = element_text(size = 34), axis.text.y = element_text(size = 26), text= element_text(family = 'Times'))



```
```{r}
# Barplot Scale för housing

r1 <- sum(with(df_tot[df_tot$housing == 1,], scale_1_5 == 1))
r2 <- sum(with(df_tot[df_tot$housing == 1,], scale_1_5 == 2))
r3 <- sum(with(df_tot[df_tot$housing == 1,], scale_1_5 == 3))
r4 <- sum(with(df_tot[df_tot$housing == 1,], scale_1_5 == 4))
r5 <- sum(with(df_tot[df_tot$housing == 1,], scale_1_5 == 5))

rating <- data.frame(numbers = c(r1, r2, r3, r4, r5), scale = 1:5)

ggplot(rating, aes(x=scale, y=numbers )) + 
  geom_bar(fill = "slategray", width = 0.7, stat = "identity", position = 'dodge') +
  geom_text(aes(label=numbers), position=position_dodge(width=0.9), vjust=-0.25,  size=11, family = 'Times') +
  theme(axis.text.x = element_text(angle = 60, vjust = 0.5)) +
  theme_minimal() +
   ylim(0, 100) +
  xlab('Rating of housing') +
  ylab(NULL) +
  theme(axis.text.x = element_text(size = 26), 
        axis.title.x = element_text(size = 34), axis.text.y = element_text(size = 26), text= element_text(family = 'Times'))

```
```{r}
r1 <- sum(with(df_tot[df_tot$atumn == 1,], scale_1_5 == 1))
r2 <- sum(with(df_tot[df_tot$atumn == 1,], scale_1_5 == 2))
r3 <- sum(with(df_tot[df_tot$atumn == 1,], scale_1_5 == 3))
r4 <- sum(with(df_tot[df_tot$atumn == 1,], scale_1_5 == 4))
r5 <- sum(with(df_tot[df_tot$atumn == 1,], scale_1_5 == 5))

rating <- data.frame(numbers = c(r1, r2, r3, r4, r5), scale = 1:5)

ggplot(rating, aes(x=scale, y=numbers )) + 
  geom_bar(fill = "slategray", width = 0.7, stat = "identity", position = 'dodge') +
  geom_text(aes(label=numbers), position=position_dodge(width=0.9), vjust=-0.25,  size=11, family = 'Times') +
  theme(axis.text.x = element_text(angle = 60, vjust = 0.5)) +
  theme_minimal() +
   ylim(0, 65) +
  xlab('Rating of atumn') +
  ylab(NULL) +
  theme(axis.text.x = element_text(size = 26), 
        axis.title.x = element_text(size = 34), axis.text.y = element_text(size = 26), text= element_text(family = 'Times'))
```

```{r}
r1 <- sum(with(df_tot[df_tot$boxes == 1,], scale_1_5 == 1))
r2 <- sum(with(df_tot[df_tot$boxes == 1,], scale_1_5 == 2))
r3 <- sum(with(df_tot[df_tot$boxes == 1,], scale_1_5 == 3))
r4 <- sum(with(df_tot[df_tot$boxes == 1,], scale_1_5 == 4))
r5 <- sum(with(df_tot[df_tot$boxes == 1,], scale_1_5 == 5))

rating <- data.frame(numbers = c(r1, r2, r3, r4, r5), scale = 1:5)

ggplot(rating, aes(x=scale, y=numbers )) + 
  geom_bar(fill = "slategray", width = 0.7, stat = "identity", position = 'dodge') +
  geom_text(aes(label=numbers), position=position_dodge(width=0.9), vjust=-0.25,  size=11, family = 'Times' ) +
  theme_minimal() +
  ylim(0, 80) +
  xlab('Rating of banruptcy') +
  ylab(NULL) +
  theme(axis.text.x = element_text(size = 26), 
        axis.title.x = element_text(size = 34), axis.text.y = element_text(size = 26), text= element_text(family = 'Times'))
```

```{r}
# Split dfs 
df_atumn <- df_tot[(df_tot$atumn == 1),]
df_housing <- df_tot[(df_tot$housing == 1),]
df_boxes <- df_tot[(df_tot$boxes == 1),]
df_atbox <- df_tot[(df_tot$atumn == 1| (df_tot$boxes == 1)),]

# Dataset with images that were pubilshed

df_publish <- df_tot[df_tot$publish_bin == 1, ]

df_housing_4 <- df_housing[df_housing$scale_1_5 == 4,]

df_worst <- df_tot[df_tot$scale_1_5 == 1,]

pub_atumn <- sum(with(df_publish, prompt == 'weather'))
pub_boxes <- sum(with(df_publish, prompt == 'bankruptcy'))
pub_housing <- sum(with(df_publish, prompt == 'houseing'))

yes_pub <- data.frame(numbers = c(pub_atumn, pub_boxes, pub_housing), cat = c('Atumn', 'Bankruptcy', 'Housing'))

ggplot(yes_pub, aes(x=cat, y=numbers )) + 
  geom_bar(fill = "slategray", width = 0.7, stat = "identity", position = 'dodge') +
  geom_text(aes(label=numbers), position=position_dodge(width=0.9), vjust=-0.25, size=12, family = 'Times')  +
  theme_minimal() +
  ylim(0, 15) +
  xlab(NULL) +
  ylab("Publishable images") +
  theme(axis.text.x = element_text(size = 26), 
        axis.title.y = element_text(size = 34), axis.text.y = element_text(size = 26), text= element_text(family = 'Times'))


```



```{r}
# Korrelationsmatris

cormat <- cor(df_tot[c(10,4:9)])

kable(cormat, caption = "Table X Correlation matrix of the variables", digits = 4,
      booktabs = TRUE, align ='c',  position = "h!") %>%
   kable_styling(latex_options = "striped")

```


```{r}
### Ordinal reg ###


# df_tot
df_tot$guidance2 <- df_tot$guidance^2
df_tot$log_inf_steps <- log(df_tot$inf_steps)
df_tot$scale_1_5 <- as.factor(df_tot$scale_1_5)
df_tot$log_inf_steps <- log(df_tot$inf_steps)

# Ordinal regression, alternativt log(inf_steps) då det är mer rimligt och blir samma resultat
ord.output <- polr(scale_1_5 ~ guidance + guidance2 + log_inf_steps + xtra_prompt + atumn + boxes,
                   data = df_tot, Hess = T)

ctable <- coef(summary(ord.output))
p <- pnorm(abs(ctable[, "t value"]), lower.tail = FALSE) * 2
ctable <- cbind(ctable, "p value" = p)
ctable <- ctable[,c(1:2, 4)]

# Reg table (Lägg till N?)
kable(ctable, caption = "Table X Ordinal logistic regression results", digits = 4,
      booktabs = TRUE, align ='c',  position = "h!", col.names = c('Estimate', 'Std. error', 'P-value')) %>%
     column_spec(1,width = '3cm') %>%
      column_spec(2,width = '2cm') %>%
      column_spec(3,width = '2cm') %>%
      column_spec(4,width = '2cm') %>%
   kable_styling(latex_options = "striped")

```

```{r}
# Regression med endast atumn och boxes

# df_atbox
df_atbox$scale_1_5 <- as.factor(df_atbox$scale_1_5)
df_atbox$guidance2 <- df_atbox$guidance^2

ord.output_atbox <- polr(scale_1_5 ~ guidance + guidance2 + log(inf_steps) + xtra_prompt + atumn,
                   data = df_atbox)

ctable_atbox <- coef(summary(ord.output_atbox))
p <- pnorm(abs(ctable_atbox[, "t value"]), lower.tail = FALSE) * 2
ctable_atbox <- cbind(ctable_atbox, "p value" = p)

# Reg table (Lägg till N?)
kable(ctable_atbox, caption = "Table X Ordinal logistic regression results excluding housing", digits = 4,
      booktabs = TRUE, align ='c',  position = "h!") %>%
     column_spec(1,width = '3cm') %>%
      column_spec(2,width = '2cm') %>%
      column_spec(3,width = '2cm') %>%
      column_spec(4,width = '2cm') %>%
      column_spec(5,width = '2cm') %>%
   kable_styling(latex_options = "striped")
```


```{r}
# Odds ratio
oddsratio <- exp(ord.output$coefficients)

kable(oddsratio, caption = "Table X Odds ratio of the coefficients", digits = 4,
      booktabs = TRUE, align ='c',  position = "h!", col.names = 'Odds ratio') %>%
     column_spec(1,width = '3cm') %>%
      column_spec(2,width = '2cm') %>%
   kable_styling(latex_options = "striped")
```


```{r}
# Reg cont.

Nobs <- nrow(df_tot)

#Compute confusion table and misclassification error
rating_pred <- predict(ord.output)
confmx <- table(df_tot$scale_1_5, rating_pred)

hit_rate <- sum(diag(confmx))/nrow(df_tot)
max_chance <- sum(with(df_tot, scale_1_5 == 1))/nrow(df_tot)
prop_chance <- sum((prop.table(table(df_tot$scale_1_5)))^2)

# Refer to Hair et al. (2010, p. 265)
random_guess_max <- 1.25*max_chance
random_guess_prop <- 1.25*prop_chance

# Proportional odds test 
clm.model <- clm(scale_1_5 ~ guidance + guidance2 + log_inf_steps + xtra_prompt + atumn + boxes,
                   data = df_tot)

prop_test1 <- nominal_test(clm.model)


prop_test2 <- brant(ord.output)

prop_odds_test <- cbind(prop_test1[5], prop_test2[,3])

kable(prop_odds_test, caption = "Test of proportional odds assumption", digits = 4,
      booktabs = TRUE, align ='c',  position = "h!", col.names = c('Nominal test', 'Brant test')) %>%
      column_spec(1,width = '3cm') %>%
      column_spec(2,width = '3cm') %>%
      column_spec(2,width = '3cm') %>%
   kable_styling(latex_options = "striped")

```

```{r}
## Fit measures ##
# mcfadden <- PseudoR2(x = ord.output, which = "McFadden")

library('gofcat')

# Ugbas modified Mcfadden measure med log eller squared penalty
ugba_R2 <- Rsquared(ord.output, measure = 'ugba')


# Gör tabell av de två testen
# Hosmer–Lemeshow test
hosmer <- hosmerlem(ord.output)

# Lipsitz likelihood-ratio test
lipsitz <- lipsitz(ord.output)

fit_test <- as.data.frame(rbind(c(hosmer$chi.sq, hosmer$df, hosmer$p.value), c( lipsitz$LRT, lipsitz$df, lipsitz$p.value)), row.names = c('Hosmer Lemeshaw test', 'Lipsitz test'))

kable(fit_test, caption = "Goodness-of-fit test", digits = 4,
      booktabs = TRUE, align ='c',  position = "h!", col.names = c('Chi-square', 'Df', 'P-value')) %>%
      column_spec(1,width = '4cm') %>%
      column_spec(2,width = '3cm') %>%
      column_spec(3,width = '3cm') %>%
      column_spec(4,width = '3cm') %>%
   kable_styling(latex_options = "striped")

```


```{r}
# Atumn

pred1 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 1, guidance2 = 1^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))

pred2 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 2, guidance2 = 2^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))

pred3 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 3, guidance2 = 3^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))

pred4 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 4, guidance2 = 4^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))


pred5 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 5, guidance2 = 5^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))


pred6 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 6, guidance2 = 6^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))


pred7 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 7, guidance2 = 7^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))


pred8 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 8, guidance2 = 8^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))


pred9 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 9, guidance2 = 9^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))


pred10 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 10, guidance2 = 10^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))


pred11 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 11, guidance2 = 11^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))


pred12 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 12, guidance2 = 12^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))


pred13 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 13, guidance2 = 13^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))


pred14 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 14, guidance2 = 14^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))


pred15 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 15, guidance2 = 15^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))


pred16 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 16, guidance2 = 16^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))


pred17 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 17, guidance2 = 17^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))


pred18 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 18, guidance2 = 18^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))


pred19 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 19, guidance2 = 19^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))


pred20 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 20, guidance2 = 20^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))


df_pred_atumn <- data.frame(pred.prob4 = c(pred1[4], pred2[4], pred3[4], pred4[4], pred5[4], pred6[4], pred7[4], pred8[4], pred9[4], pred10[4], pred11[4], pred12[4], pred13[4], pred14[4], pred15[4], pred16[4], pred17[4], pred18[4], pred19[4], pred20[4] ),
                      guidance = 1:20)


df_pred_atumn$pred.prob5 <- c(pred1[5], pred2[5], pred3[5], pred4[5], pred5[5], pred6[5], pred7[5], pred8[5], pred9[5], pred10[5], pred11[5], pred12[5], pred13[5], pred14[5], pred15[5], pred16[5], pred17[5], pred18[5], pred19[5], pred20[5] )

df_pred_atumn$pred.prob2 <-  c(pred1[2], pred2[2], pred3[2], pred4[2], pred5[2], pred6[2], pred7[2], pred8[2], pred9[2], pred10[2], pred11[2], pred12[2], pred13[2], pred14[2], pred15[2], pred16[2], pred17[2], pred18[2], pred19[2], pred20[2])


```

```{r}
# Plot atumn guidance maximum 

ggplot(df_pred_atumn, aes(x=guidance, y=pred.prob4)) +
  geom_line() +
  geom_point() 

ggplot(df_pred_atumn, aes(x=guidance, y=pred.prob2)) +
  geom_line() +
  geom_point() 

ggplot(df_pred_atumn, aes(x=guidance, y=pred.prob5)) +
  geom_line() +
  geom_point() +
  theme_gray() +
  theme(plot.title = element_text(size = 24), axis.title = element_text(size = 24),
        axis.text.x = element_text(size = 20), axis.text.y  = element_text(size = 20)) +
  ylab('Predicted Pr(rating 5) ') +
  xlab('Guidance') +
  labs( title = 'Weather')


```


```{r}
# Boxes 
pred1 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 1, guidance2 = 1^2, log_inf_steps = log(50), xtra_prompt = 0, atumn =0, boxes = 1))

pred2 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 2, guidance2 = 2^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 1))

pred3 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 3, guidance2 = 3^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 1))

pred4 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 4, guidance2 = 4^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 1))


pred5 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 5, guidance2 = 5^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 1))


pred6 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 6, guidance2 = 6^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 1))


pred7 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 7, guidance2 = 7^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 1))


pred8 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 8, guidance2 = 8^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 1))


pred9 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 9, guidance2 = 9^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 1))


pred10 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 10, guidance2 = 10^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 1))


pred11 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 11, guidance2 = 11^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 1))


pred12 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 12, guidance2 = 12^2, log_inf_steps = log(50), xtra_prompt = 0,atumn = 0, boxes = 1))


pred13 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 13, guidance2 = 13^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 1))


pred14 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 14, guidance2 = 14^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 1))


pred15 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 15, guidance2 = 15^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 1))


pred16 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 16, guidance2 = 16^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 1))


pred17 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 17, guidance2 = 17^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 1))


pred18 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 18, guidance2 = 18^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 1))


pred19 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 19, guidance2 = 19^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 1))


pred20 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 20, guidance2 = 20^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 1))

df_pred_boxes <- data.frame(pred.prob4 = c(pred1[4], pred2[4], pred3[4], pred4[4], pred5[4], pred6[4], pred7[4], pred8[4], pred9[4], pred10[4], pred11[4], pred12[4], pred13[4], pred14[4], pred15[4], pred16[4], pred17[4], pred18[4], pred19[4], pred20[4] ),
                      guidance = 1:20)

df_pred_boxes$pred.prob5 <- c(pred1[5], pred2[5], pred3[5], pred4[5], pred5[5], pred6[5], pred7[5], pred8[5], pred9[5], pred10[5], pred11[5], pred12[5], pred13[5], pred14[5], pred15[5], pred16[5], pred17[5], pred18[5], pred19[5], pred20[5] )

df_pred_boxes$pred.prob2 <-  c(pred1[2], pred2[2], pred3[2], pred4[2], pred5[2], pred6[2], pred7[2], pred8[2], pred9[2], pred10[2], pred11[2], pred12[2], pred13[2], pred14[2], pred15[2], pred16[2], pred17[2], pred18[2], pred19[2], pred20[2])

```


```{r}
# Plot boxes guidance maximum

ggplot(df_pred_boxes, aes(x=guidance, y=pred.prob4)) +
  geom_line() +
  geom_point()

ggplot(df_pred_boxes, aes(x=guidance, y=pred.prob2)) +
  geom_line() +
  geom_point()

ggplot(df_pred_boxes, aes(x=guidance, y=pred.prob5)) +
  geom_line() +
  geom_point()  +
  theme_gray() +
  theme(plot.title = element_text(size = 24), axis.title = element_text(size = 24),
        axis.text.x = element_text(size = 20), axis.text.y  = element_text(size = 20)) +
  ylab('Predicted Pr(rating 5) ') +
  xlab('Guidance') +
  labs( title = 'Bankruptcy')


```

```{r}
# Housing

pred1 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 1, guidance2 = 1^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))

pred2 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 2, guidance2 = 2^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))

pred3 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 3, guidance2 = 3^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))

pred4 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 4, guidance2 = 4^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))


pred5 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 5, guidance2 = 5^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))


pred6 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 6, guidance2 = 6^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))


pred7 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 7, guidance2 = 7^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))


pred8 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 8, guidance2 = 8^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))


pred9 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 9, guidance2 = 9^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))


pred10 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 10, guidance2 = 10^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))


pred11 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 11, guidance2 = 11^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))


pred12 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 12, guidance2 = 12^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))


pred13 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 13, guidance2 = 13^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))


pred14 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 14, guidance2 = 14^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))


pred15 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 15, guidance2 = 15^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))


pred16 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 16, guidance2 = 16^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))


pred17 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 17, guidance2 = 17^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))


pred18 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 18, guidance2 = 18^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))


pred19 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 19, guidance2 = 19^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))


pred20 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 20, guidance2 = 20^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))

df_pred_housing <- data.frame(pred.prob4 = c(pred1[4], pred2[4], pred3[4], pred4[4], pred5[4], pred6[4], pred7[4], pred8[4], pred9[4], pred10[4], pred11[4], pred12[4], pred13[4], pred14[4], pred15[4], pred16[4], pred17[4], pred18[4], pred19[4], pred20[4] ),
                      guidance = 1:20)

df_pred_housing$pred.prob5 <- c(pred1[5], pred2[5], pred3[5], pred4[5], pred5[5], pred6[5], pred7[5], pred8[5], pred9[5], pred10[5], pred11[5], pred12[5], pred13[5], pred14[5], pred15[5], pred16[5], pred17[5], pred18[5], pred19[5], pred20[5] )

df_pred_housing$pred.prob2 <-  c(pred1[2], pred2[2], pred3[2], pred4[2], pred5[2], pred6[2], pred7[2], pred8[2], pred9[2], pred10[2], pred11[2], pred12[2], pred13[2], pred14[2], pred15[2], pred16[2], pred17[2], pred18[2], pred19[2], pred20[2])

df_pred_housing$pred.prob1 <-  c(pred1[1], pred2[1], pred3[1], pred4[1], pred5[1], pred6[1], pred7[1], pred8[1], pred9[1], pred10[1], pred11[1], pred12[1], pred13[1], pred14[1], pred15[1], pred16[1], pred17[1], pred18[1], pred19[1], pred20[1])

```

```{r}
# Plot housing guidance maximum

ggplot(df_pred_housing, aes(x=guidance, y=pred.prob4)) +
  geom_line() +
  geom_point()

ggplot(df_pred_housing, aes(x=guidance, y=pred.prob2)) +
  geom_line() +
  geom_point()

ggplot(df_pred_housing, aes(x=guidance, y=pred.prob1)) +
  geom_line() +
  geom_point()

ggplot(df_pred_housing, aes(x=guidance, y=pred.prob5)) +
  geom_line() +
  geom_point()  +
  theme_gray() +
  theme(plot.title = element_text(size = 24), axis.title = element_text(size = 24),
        axis.text.x = element_text(size = 20), axis.text.y  = element_text(size = 20)) +
  ylab('Predicted Pr(rating 5) ') +
  xlab('Guidance') +
  labs( title = 'Housing market')
```

```{r}

ind1 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 10, guidance2 = 10^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))

ind2 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 3, guidance2 = 3^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 1, boxes = 0))

ind3 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 10, guidance2 = 10^2, log_inf_steps = log(150), xtra_prompt = 0, atumn = 1, boxes = 0))

ind4 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 10, guidance2 = 10^2, log_inf_steps = log(50), xtra_prompt = 1, atumn = 1, boxes = 0))

ind5 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 10, guidance2 = 10^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 1))

ind6 <- predict(ord.output, type = 'prob',
        newdata = data.frame(guidance = 10, guidance2 = 10^2, log_inf_steps = log(50), xtra_prompt = 0, atumn = 0, boxes = 0))


p1 <- cbind(10, "10^2", "log(50)", 0, 1, 0, round(ind1[4], 4))
p2 <- cbind(3, "3^2", "log(50)", 0, 1, 0, round(ind2[4], 4))
p3 <- cbind(10, "10^2", "log(150)", 0, 1, 0, round(ind3[4], 4))
p4 <- cbind(10, "10^2", "log(50)", 1, 1, 0, round(ind4[4], 4))
p5 <- cbind(10, "10^2", "log(50)", 0, 0, 1, round(ind5[4], 4))
p6 <- cbind(10, "10^2", "log(50)", 0, 0, 0, round(ind6[4], 4))

pred_tab <- rbind(p1, p2, p3, p4, p5, p6)

kable(pred_tab, caption = "Predicted individuals",
      booktabs = TRUE, align ='c',
      col.names = c('Guidance', 'Guidance^2', 'Iterations', 'Keywords', 'AtumnD', 'BoxesD', 'Prob. rating 4'),
      position = "h!") %>%
   kable_styling(latex_options = "striped")

```

```{r}
df_prob <- data.frame(prob = c(ind1[4], ind2[4], ind3[4], ind4[4], ind5[4], ind6[4]), ind = 1:6)


ggplot(df_prob, aes(x=ind, y=prob)) +
  geom_line() +
  geom_point()  +
  theme_gray() +
#  theme(plot.title = element_text(size = 24), axis.title = element_text(size = 24),
 #       axis.text.x = element_text(size = 20), axis.text.y  = element_text(size = 20)) +
  ylab('Predicted Pr(rank 4) ') +
  xlab('Individual') 
```

```{r}

df_tot$fitted5 <- ord.output$fitted.values[,5]

ggplot(df_tot, aes(x=guidance, y=(fitted5))) +
  geom_point()  +
  theme_gray() +
  theme(plot.title = element_text(size = 24), axis.title = element_text(size = 22),
        axis.text.x = element_text(size = 20), axis.text.y  = element_text(size = 20)) +
  ylab('Predicted Pr(rating 5)') +
  xlab('Guidance')  +
  theme(axis.text.x = element_text(size = 26), 
        axis.title.y = element_text(size = 31), axis.text.y = element_text(size = 26), text= element_text(family = 'Times'))

ggplot(df_tot, aes(x=inf_steps, y=(fitted5))) +
  geom_point()  +
  theme_gray() +
  theme(plot.title = element_text(size = 24), axis.title = element_text(size = 22),
        axis.text.x = element_text(size = 20), axis.text.y  = element_text(size = 20)) +
  ylab('Predicted Pr(rating 5)') +
  xlab('Iterations')  +
  theme(axis.text.x = element_text(size = 26), 
        axis.title.y = element_text(size = 31), axis.text.y = element_text(size = 26), text= element_text(family = 'Times'))

ggplot(df_tot, aes(x=xtra_prompt, y=(fitted5))) +
  geom_point()  +
  theme_gray() +
  theme(plot.title = element_text(size = 24), axis.title = element_text(size = 22),
        axis.text.x = element_text(size = 20), axis.text.y  = element_text(size = 20)) +
  ylab('Predicted Pr(rating 5)') +
  xlab('Keywords')  +
  theme(axis.text.x = element_text(size = 26), 
        axis.title.y = element_text(size = 31), axis.text.y = element_text(size = 26), text= element_text(family = 'Times'))

ggplot(df_tot, aes(x=atumn, y=(fitted5))) +
  geom_point()  +
  theme_gray() +
  theme(plot.title = element_text(size = 24), axis.title = element_text(size = 22),
        axis.text.x = element_text(size = 20), axis.text.y  = element_text(size = 20)) +
  ylab('Predicted Pr(rating 5)') +
  xlab('Weather')  +
  theme(axis.text.x = element_text(size = 26), 
        axis.title.y = element_text(size = 31), axis.text.y = element_text(size = 26), text= element_text(family = 'Times'))

ggplot(df_tot, aes(x=boxes, y=(fitted5))) +
  geom_point()  +
  theme_gray() +
  theme(plot.title = element_text(size = 24), axis.title = element_text(size = 22),
        axis.text.x = element_text(size = 20), axis.text.y  = element_text(size = 20)) +
  ylab('Predicted Pr(rating 5)') +
  xlab('Bankruptcy')  +
  theme(axis.text.x = element_text(size = 26), 
        axis.title.y = element_text(size = 31), axis.text.y = element_text(size = 26), text= element_text(family = 'Times'))


ggplot(df_tot, aes(x=housing, y=(fitted5))) +
  geom_point()  +
  theme_gray() +
  theme(plot.title = element_text(size = 24), axis.title = element_text(size = 22),
        axis.text.x = element_text(size = 20), axis.text.y  = element_text(size = 20)) +
  ylab('Predicted Pr(rating 5)') +
  xlab('Housing') +
  theme(axis.text.x = element_text(size = 26), 
        axis.title.y = element_text(size = 31), axis.text.y = element_text(size = 26), text= element_text(family = 'Times'))


```

